# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180424_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.ImageField(upload_to=questions.models.upload_question_image_location),
        ),
    ]
