# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180424_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
