# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180425_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_time',
        ),
    ]
