# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180425_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_time',
        ),
    ]
