# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=grader.models.upload_solution_file_location)),
                ('language', models.CharField(max_length=10)),
                ('result', models.CharField(blank=True, choices=[('ac', 'AC'), ('wa', 'WA'), ('tle', 'TLE'), ('cte', 'CTE'), ('sigabrt', 'SIGABRT')], max_length=10, null=True)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'timestamp'],
            },
        ),
    ]
