# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_auto_20180425_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='solution',
            name='total_time',
        ),
    ]
